Modify configure-blacksmith to include plan parameters
blacksmith-community/redis-forge-boshrelease pull request #13
Opened 2020-10-21 01:12 UTC by norman-abramovitz

Changed configure_blacksmith to include the client parameters when the merge meta file is generated.

2020-10-23 17:34 UTC, thomasmitchell requested changes

2020-10-23 17:34 UTC, thomasmitchell commented on README.md
> +This avoids Redis users from overriding the predefined Redis plan parameters.
I would just cut out line 237. 236 suffices.

2020-10-23 17:34 UTC, thomasmitchell commented on jobs/cluster/templates/config/redis.conf
> +auto-aof-rewrite-min-size "<%= p('redis.auto-aof-rewrite-min-size') %>"
don't quote this

2020-10-23 17:34 UTC, thomasmitchell commented on jobs/cluster/templates/config/redis.conf
> +auto-aof-rewrite-percentage "<%= p('redis.auto-aof-rewrite-percentage') %>"
don't quote this

2020-10-23 17:34 UTC, thomasmitchell commented on jobs/cluster/spec
> +    default: "no"
let's make this a true/false boolean in the YAML. Especially because there's a potential gotcha here, as certain versions of YAML will interpret a non-quoted `yes` as the boolean `true` and an unquoted `no` as the boolean `false`.

2020-10-23 17:34 UTC, thomasmitchell commented on jobs/redis-blacksmith-plans/templates/bin/configure-blacksmith
> +  <% if plan["redis_no-appendfsync-on-rewrite"] %>
let's turn this key into a boolean in yaml as well. This line is still fine after it's turned into a boolean though.

2020-10-23 17:34 UTC, thomasmitchell commented on jobs/redis-blacksmith-plans/templates/bin/configure-blacksmith
> +  redis_no-appendfsync-on-rewrite <%= plan["redis_no-appendfsync-on-rewrite"] %>
You're missing a colon here to make it a YAML key/value. Also, when this is changed to a boolean, the ERB value should be changed to a ternary statement like 
```erb
<%= plan["redis_no-appendfsync-on-rewrite"] ? "yes" : "no" %>
```

2020-10-23 17:34 UTC, thomasmitchell commented on jobs/redis-blacksmith-plans/templates/bin/configure-blacksmith
> +  <% end %>
more concisely:
```suggestion
  lua_scripting_enabled: <%= !!plan["lua_scripting_enabled"] %>
```

2020-10-23 17:34 UTC, thomasmitchell commented on jobs/redis-blacksmith-plans/templates/plans/cluster/manifest.yml
> +            no-appendfsync-on-rewrite: (( grab meta.redis_no-appendfsync-on-rewrite || "no" ))
if this is turned into a boolean, then this becomes
```
no-appendfsync-on-rewrite: (( grab meta.redis_no-appendfsync-on-rewrite || false ))
```

2020-10-23 17:34 UTC, thomasmitchell commented on jobs/redis-blacksmith-plans/templates/plans/standalone/manifest.yml
> +            no-appendfsync-on-rewrite: (( grab meta.redis_no-appendfsync-on-rewrite || "no" ))
if this is turned into a boolean, then this becomes
```
no-appendfsync-on-rewrite: (( grab meta.redis_no-appendfsync-on-rewrite || false ))
```

2020-10-23 17:34 UTC, thomasmitchell commented on jobs/standalone/spec
> +  redis.no-appendfsync-on-rewrite:
as has been said a bunch above, let's make this a YAML boolean.

2020-10-23 17:34 UTC, thomasmitchell commented on jobs/standalone/templates/config/redis.conf
> +<% end %>
once this is changed to a boolean, simply
```
no-appendfsync-on-rewrite <%= p('redis.no-appendfsync-on-rewrite') %> ? "yes" : "no" %>
```

2020-10-23 17:34 UTC, thomasmitchell commented on jobs/standalone/templates/config/redis.conf
> +auto-aof-rewrite-percentage "<%= p('redis.auto-aof-rewrite-percentage') %>"
don't quote the erb value

2020-10-23 17:34 UTC, thomasmitchell commented on jobs/standalone/templates/config/redis.conf
> +auto-aof-rewrite-min-size "<%= p('redis.auto-aof-rewrite-min-size') %>"
don't quote the erb value

2020-10-23 17:34 UTC, thomasmitchell commented on jobs/standalone/templates/config/redis.conf
> +
drop this comment. It's not really by request. This is a reasonable boundary for user of a service vs operator of a service

2020-10-23 17:34 UTC, thomasmitchell commented on jobs/cluster/templates/config/redis.conf
> +<% end %>
once this is changed to a boolean, simply:
```
no-appendfsync-on-rewrite <%= p('redis.no-appendfsync-on-rewrite') %> ? "yes" : "no" %>
```

notably, also drop the erb value quotes.

2020-10-23 17:47 UTC, norman-abramovitz commented on jobs/cluster/templates/config/redis.conf
> +auto-aof-rewrite-min-size "<%= p('redis.auto-aof-rewrite-min-size') %>"
Interesting quotes did cause any issues, but I will make the change.

2020-10-23 19:10 UTC, norman-abramovitz commented on README.md
> +This avoids Redis users from overriding the predefined Redis plan parameters.
done

2020-10-23 23:53 UTC, norman-abramovitz commented on jobs/standalone/templates/config/redis.conf
> +auto-aof-rewrite-min-size "<%= p('redis.auto-aof-rewrite-min-size') %>"
fixed

2020-10-23 23:55 UTC, norman-abramovitz commented
@thomasmitchell  Ready for your next review.

2020-10-26 13:55 UTC, thomasmitchell approved these changes

2020-10-26 13:55 UTC, merged